### ISSUE TITLE
Looking for research backing

### ISSUE THREAD

**Issue by joereddington** [otsimo/autism-colors#2]
Hi there, 

Can you point out some of the research that you used building this tool? It would help me make a much stronger case to other people that they should use it. 

Joe

**Comment by btk** [comment]
Hey @joereddington, 

It is funny but; the research we used for this was done by an architecture company that focuses on designing interior of the buildings for especially kids with autism.

"A group study done by GA Architects states that using soft, calm and dark colors while designing interior design for rooms created for kids with autism, helps kids to focus more and allow them to have a longer session of studing."

<http://www.autism-architects.com/wp-content/uploads/downloads/2012/06/CB-Presentation-Catania-2010.pdf>

Check page 8. Also I'm adding this pdf file to readme.

If you are on the mission to design UI for autism, you might wanna check [this medium](https://nerds.otsimo.com/designing-ui-ux-for-children-with-autism-in-touch-devices-bdd4c7741586) post I wrote a year ago. 

If you have additional question you can email me at iletisim@buraktokak.com

**Comment by zaferelcik** [comment]
Closed 👍
